#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from vulnagentx.eval.detection_metrics import compute_detection_metrics
from vulnagentx.eval.efficiency_metrics import compute_efficiency_metrics
from vulnagentx.eval.localization_metrics import compute_localization_metrics


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate VulnAgent-X experiment outputs")
    parser.add_argument("--predictions", required=True, help="JSONL generated by run_experiment.py")
    parser.add_argument("--output", default=None, help="Optional JSON file to write metrics")
    args = parser.parse_args()

    labels: list[int] = []
    preds: list[int] = []
    gold_locations: list[list[str]] = []
    predicted_locations: list[list[str]] = []
    runtimes: list[float] = []
    findings_count: list[int] = []

    with Path(args.predictions).open("r", encoding="utf-8") as handle:
        for line in handle:
            raw = line.strip()
            if not raw:
                continue
            item = json.loads(raw)
            labels.append(int(item.get("label", 0)))
            preds.append(int(item.get("prediction", 0)))
            gold_locations.append([str(x) for x in item.get("gold_locations", [])])
            predicted_locations.append([str(x) for x in item.get("predicted_locations", [])])
            metrics = item.get("metrics", {})
            runtime = metrics.get("runtime_seconds", 0.0) if isinstance(metrics, dict) else 0.0
            runtimes.append(float(runtime))
            findings_count.append(len(item.get("findings", [])))

    detection = compute_detection_metrics(labels, preds)
    localization = compute_localization_metrics(gold_locations, predicted_locations)
    efficiency = compute_efficiency_metrics(runtimes, findings_count)

    report = {
        "detection": detection.__dict__,
        "localization": localization.__dict__,
        "efficiency": efficiency.__dict__,
        "samples": len(labels),
    }

    content = json.dumps(report, ensure_ascii=False, indent=2)
    print(content)

    if args.output:
        Path(args.output).write_text(content + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
